ssg_news_index:
    path:     /news
    defaults: { _controller: SSGNewsBundle:News:index }

ssg_news_add:
    path:     /news/add
    defaults: { _controller: SSGNewsBundle:News:add }

ssg_news_view:
    path:     /news/{id}
    defaults: { _controller: SSGNewsBundle:News:view }
    requirements:
        id: \d+

ssg_news_edit:
    path:     /news/edit/{id}
    defaults: { _controller: SSGNewsBundle:News:edit }
    requirements:
            id: \d+

ssg_news_delete:
    path:     /news/delete/{id}
    defaults: { _controller: SSGNewsBundle:News:delete }
    requirements:
            id: \d+