<?php

namespace SSG\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getNews($page, $nbPerPage) {
        $query = $this->createQueryBuilder('a')->orderBy('a.id', 'DESC')->getQuery();
        $query->setFirstResult(($page-1) * $nbPerPage);
        $query->setMaxResults($nbPerPage);
        return new Paginator($query, true);
    }

    public function getNewsById($id) {
        $query = $this->createQueryBuilder('a')->where('a.id = '.$id)->getQuery();
        return $query->getOneOrNullResult();
    }

}
